
package com.server.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.2.7
 * Tue Jan 15 16:27:53 IST 2019
 * Generated source version: 3.2.7
 */

@XmlRootElement(name = "getPersonResponse", namespace = "http://server.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getPersonResponse", namespace = "http://server.com/")

public class GetPersonResponse {

    @XmlElement(name = "return")
    private com.server.model.Person _return;

    public com.server.model.Person getReturn() {
        return this._return;
    }

    public void setReturn(com.server.model.Person new_return)  {
        this._return = new_return;
    }

}

