
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.server;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-01-15T16:30:23.159+05:30
 * Generated source version: 3.2.7
 *
 */

@javax.jws.WebService(
                      serviceName = "PersonServiceImplService",
                      portName = "PersonServiceImplPort",
                      targetNamespace = "http://server.com/",
                      wsdlLocation = "http://localhost:8080/StocksModule/services/personservice?wsdl",
                      endpointInterface = "com.server.PersonSEI")

public class PersonServiceImplPortImpl implements PersonSEI {

    private static final Logger LOG = Logger.getLogger(PersonServiceImplPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.server.PersonSEI#getPerson(int arg0)*
     */
    public com.server.Person getPerson(int arg0) {
        LOG.info("Executing operation getPerson");
        System.out.println(arg0);
        try {
            com.server.Person _return = new com.server.Person();
            _return.setGrade(0.5423440643618861);
            _return.setId(957369557);
            _return.setName("Name1808232810");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.server.PersonSEI#updatePerson(com.server.Person arg0, int arg1)*
     */
    public boolean updatePerson(com.server.Person arg0, int arg1) {
        LOG.info("Executing operation updatePerson");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            boolean _return = true;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
