package com.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-01-15T16:30:23.182+05:30
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://server.com/", name = "PersonSEI")
@XmlSeeAlso({ObjectFactory.class})
public interface PersonSEI {

    @WebMethod
    @RequestWrapper(localName = "getPerson", targetNamespace = "http://server.com/", className = "com.server.GetPerson")
    @ResponseWrapper(localName = "getPersonResponse", targetNamespace = "http://server.com/", className = "com.server.GetPersonResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.server.Person getPerson(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebMethod
    @RequestWrapper(localName = "updatePerson", targetNamespace = "http://server.com/", className = "com.server.UpdatePerson")
    @ResponseWrapper(localName = "updatePersonResponse", targetNamespace = "http://server.com/", className = "com.server.UpdatePersonResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean updatePerson(
        @WebParam(name = "arg0", targetNamespace = "")
        com.server.Person arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );
}
