
package com.server;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-01-15T16:30:23.035+05:30
 * Generated source version: 3.2.7
 *
 */
public final class PersonSEI_PersonServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://server.com/", "PersonServiceImplService");

    private PersonSEI_PersonServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = PersonServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        PersonServiceImplService ss = new PersonServiceImplService(wsdlURL, SERVICE_NAME);
        PersonSEI port = ss.getPersonServiceImplPort();

        {
        System.out.println("Invoking getPerson...");
        int _getPerson_arg0 = -1045692463;
        com.server.Person _getPerson__return = port.getPerson(_getPerson_arg0);
        System.out.println("getPerson.result=" + _getPerson__return);


        }
        {
        System.out.println("Invoking updatePerson...");
        com.server.Person _updatePerson_arg0 = new com.server.Person();
        _updatePerson_arg0.setGrade(0.5891694515205688);
        _updatePerson_arg0.setId(1632006437);
        _updatePerson_arg0.setName("Name-1079435841");
        int _updatePerson_arg1 = 339243202;
        boolean _updatePerson__return = port.updatePerson(_updatePerson_arg0, _updatePerson_arg1);
        System.out.println("updatePerson.result=" + _updatePerson__return);


        }

        System.exit(0);
    }

}
