
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.server;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-01-15T15:50:21.879+05:30
 * Generated source version: 3.2.7
 *
 */

@javax.jws.WebService(
                      serviceName = "StockExchangeService",
                      portName = "StockExchangePort",
                      targetNamespace = "http://server.com/",
                      wsdlLocation = "http://localhost:8080/StocksModule/services/StockExchangePort?wsdl",
                      endpointInterface = "com.server.StockX")

public class StockExchangePortImpl implements StockX {

    private static final Logger LOG = Logger.getLogger(StockExchangePortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.server.StockX#getStockPrice(java.lang.String arg0)*
     */
    public double getStockPrice(java.lang.String arg0) {
        LOG.info("Executing operation getStockPrice");
        System.out.println(arg0);
        try {
            double _return = 0.042948210251419594;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.server.StockX#removeStock(java.lang.String arg0)*
     */
    public boolean removeStock(java.lang.String arg0) {
        LOG.info("Executing operation removeStock");
        System.out.println(arg0);
        try {
            boolean _return = true;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.server.StockX#updateStock(java.lang.String arg0, double arg1)*
     */
    public java.lang.Boolean updateStock(java.lang.String arg0, double arg1) {
        LOG.info("Executing operation updateStock");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            java.lang.Boolean _return = Boolean.valueOf(false);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
