package com.server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-01-15T15:50:21.958+05:30
 * Generated source version: 3.2.7
 *
 */
@WebServiceClient(name = "StockExchangeService",
                  wsdlLocation = "http://localhost:8080/StocksModule/services/StockExchangePort?wsdl",
                  targetNamespace = "http://server.com/")
public class StockExchangeService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://server.com/", "StockExchangeService");
    public final static QName StockExchangePort = new QName("http://server.com/", "StockExchangePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/StocksModule/services/StockExchangePort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(StockExchangeService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/StocksModule/services/StockExchangePort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public StockExchangeService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public StockExchangeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StockExchangeService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public StockExchangeService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public StockExchangeService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public StockExchangeService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns StockX
     */
    @WebEndpoint(name = "StockExchangePort")
    public StockX getStockExchangePort() {
        return super.getPort(StockExchangePort, StockX.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StockX
     */
    @WebEndpoint(name = "StockExchangePort")
    public StockX getStockExchangePort(WebServiceFeature... features) {
        return super.getPort(StockExchangePort, StockX.class, features);
    }

}
