
package com.server;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-01-15T16:27:53.253+05:30
 * Generated source version: 3.2.7
 *
 */

public class PersonSEIServer{

    protected PersonSEIServer() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new com.server.PersonServiceImpl();
        String address = "http://localhost:9090/PersonServiceImplPort";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws Exception {
        new PersonSEIServer();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}

