
package com.server;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-01-15T15:47:56.779+05:30
 * Generated source version: 3.2.7
 *
 */

public class StockXServer{

    protected StockXServer() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new com.server.StockExchange();
        String address = "http://localhost:9090/StockExchangePort";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws Exception {
        new StockXServer();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}

