
package com.server;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-01-16T11:42:04.516+05:30
 * Generated source version: 3.2.7
 *
 */
public final class IAccount_AccountPort_Client {

    private static final QName SERVICE_NAME = new QName("http://server.com/", "AccountService");

    private IAccount_AccountPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = AccountService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        AccountService ss = new AccountService(wsdlURL, SERVICE_NAME);
        IAccount port = ss.getAccountPort();

        {
        System.out.println("Invoking getDetails...");
        double _getDetails_arg0 = 0.6889091657686334;
        java.lang.String _getDetails_arg1 = "_getDetails_arg1319574456";
        int _getDetails__return = port.getDetails(_getDetails_arg0, _getDetails_arg1);
        System.out.println("getDetails.result=" + _getDetails__return);


        }
        {
        /*System.out.println("Invoking update...");
        java.lang.String _update_arg0 = "_update_arg068073877";
        port.update(_update_arg0);*/


        }

        System.exit(0);
    }

}
