<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="AccountService" targetNamespace="http://server.com/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://server.com/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:types>
    <schema xmlns="http://www.w3.org/2001/XMLSchema">
  <import namespace="http://server.com/" schemaLocation="account_schema1.xsd"/>
</schema>
  </wsdl:types>
  <wsdl:message name="getName">
    <wsdl:part name="parameters" element="tns:getName">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="readBalance">
    <wsdl:part name="parameters" element="tns:readBalance">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="getNameResponse">
    <wsdl:part name="parameters" element="tns:getNameResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="readBalanceResponse">
    <wsdl:part name="parameters" element="tns:readBalanceResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="AccountSEI">
    <wsdl:operation name="getName">
      <wsdl:input name="getName" message="tns:getName">
    </wsdl:input>
      <wsdl:output name="getNameResponse" message="tns:getNameResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="readBalance">
      <wsdl:input name="readBalance" message="tns:readBalance">
    </wsdl:input>
      <wsdl:output name="readBalanceResponse" message="tns:readBalanceResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="AccountServiceSoapBinding" type="tns:AccountSEI">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="getName">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="getName">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="getNameResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="readBalance">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="readBalance">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="readBalanceResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="AccountService">
    <wsdl:port name="AccountPort" binding="tns:AccountServiceSoapBinding">
      <soap:address location="http://localhost:8080/CXF-Service/services/AccountPort"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
