package com.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-01-15T12:16:18.793+05:30
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://server.com/", name = "AccountSEI")
@XmlSeeAlso({ObjectFactory.class})
public interface AccountSEI {

    @WebMethod
    @RequestWrapper(localName = "getName", targetNamespace = "http://server.com/", className = "com.server.GetName")
    @ResponseWrapper(localName = "getNameResponse", targetNamespace = "http://server.com/", className = "com.server.GetNameResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getName(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebMethod
    @RequestWrapper(localName = "readBalance", targetNamespace = "http://server.com/", className = "com.server.ReadBalance")
    @ResponseWrapper(localName = "readBalanceResponse", targetNamespace = "http://server.com/", className = "com.server.ReadBalanceResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String readBalance(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
