
package com.server;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-01-15T12:16:18.662+05:30
 * Generated source version: 3.2.7
 *
 */
public final class AccountSEI_AccountPort_Client {

    private static final QName SERVICE_NAME = new QName("http://server.com/", "AccountService");

    private AccountSEI_AccountPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = AccountService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        AccountService ss = new AccountService(wsdlURL, SERVICE_NAME);
        AccountSEI port = ss.getAccountPort();

        {
        System.out.println("Invoking getName...");
        int _getName_arg0 = 937644238;
        java.lang.String _getName__return = port.getName(_getName_arg0);
        System.out.println("getName.result=" + _getName__return);


        }
        {
        System.out.println("Invoking readBalance...");
        java.lang.String _readBalance_arg0 = "_readBalance_arg01857087800";
        java.lang.String _readBalance__return = port.readBalance(_readBalance_arg0);
        System.out.println("readBalance.result=" + _readBalance__return);


        }

        System.exit(0);
    }

}
